version: "3.9"
services:
  users2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - users_db
    environment:
      DB_HOST: users_db
      DB_DATABASE: users
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_PORT: 3306
    ports:
      - "8001:8001"

  users_db:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: users
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33068:3306
