version: "3.9"
services:
  checkout:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - checkout_db
    environment:
      DB_HOST: checkout_db
      DB_DATABASE: checkout
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_PORT: 3306
    command: "php artisan serve --host=0.0.0.0"
    ports:
      - 8002:8000
  queue1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: "php artisan queue:work"

  checkout_db:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: checkout
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33069:3306
