version: "3.9"
services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - admin_db
    environment:
      DB_HOST: admin_db
      DB_DATABASE: admin
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_PORT: 3306
    command: "php artisan serve --host=0.0.0.0"
    ports:
      - 8004:8000
  queue1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - admin_db
      - admin
    environment:
      DB_HOST: admin_db
      DB_DATABASE: admin
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_PORT: 3306
    command: "php artisan queue:work"

  admin_db:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33071:3306
