version: "3.9"
services:
  influencer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - influencer_db
    environment:
      DB_HOST: influencer_db
      DB_DATABASE: influencer
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_PORT: 3306
    command: "php artisan serve --host=0.0.0.0"
    ports:
      - 8003:8000
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - influencer_db
      - influencer
    environment:
      DB_HOST: influencer_db
      DB_DATABASE: influencer
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_PORT: 3306
    command: "php artisan queue:work"

  influencer_db:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: influencer
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33070:3306

  redis:
    networks:
      - app
    image: redis:7.0.0-alpine
    restart: unless-stopped
    tty: true
    ports:
      - 6379:6379